networks:
  ps2gg_internal:
    external: true
secrets:
  discord_token:
    external: true
services:
  census:
    entrypoint:
    - yarn
    - nx
    - serve
    - census
    image: 127.0.0.1:5000/ps2gg:dev
    volumes:
    - /opt/ps2gg:/app:rw
  discord:
    entrypoint:
    - yarn
    - nx
    - serve
    - discord
    image: 127.0.0.1:5000/ps2gg:dev
    networks:
      ps2gg_internal: {}
    secrets:
    - source: discord_token
    volumes:
    - /opt/ps2gg:/app:rw
  players:
    entrypoint:
    - yarn
    - nx
    - serve
    - players
    image: 127.0.0.1:5000/ps2gg:dev
    volumes:
    - /opt/ps2gg:/app:rw
version: '3.4'

