networks:
  ps2gg_internal:
    external: true
secrets:
  discord_token:
    external: true
services:
  discord:
    entrypoint:
    - sh
    - /app/services/discord/src/entrypoint.sh
    image: 127.0.0.1:5000/ps2gg:prod
    networks:
      ps2gg_internal: null
    secrets:
    - source: discord_token
    volumes:
    - /opt/planetside/ps2gg:/app:rw
version: '3.4'

