version: '3.4'
services:
  discord:
    image: 127.0.0.1:5000/ps2gg:prod
    entrypoint: [ "sh", "/app/services/discord/src/entrypoint.sh" ]
    networks:
      - ps2gg_internal
    volumes:
      - ../../:/app

networks:
  ps2gg_internal:
    external: true
