version: '3.4'
services:
  discord:
    image: 127.0.0.1:5000/ps2gg:dev
    entrypoint:
      - yarn
      - nx
      - serve
      - discord
    networks:
      - ps2gg_internal
    volumes:
      - ../../:/app

networks:
  - ps2gg_internal
