version: '3.4'
services:
  census:
    image: 127.0.0.1:5000/ps2gg:dev
    entrypoint:
      - yarn
      - nx
      - serve
      - census
    networks:
      - ps2gg_internal
    volumes:
      - ../../:/app

  players:
    image: 127.0.0.1:5000/ps2gg:dev
    entrypoint:
      - yarn
      - nx
      - serve
      - players
    networks:
      - ps2gg_internal
    volumes:
      - ../../:/app

  discord:
    image: 127.0.0.1:5000/ps2gg:dev
    entrypoint:
      - yarn
      - nx
      - serve
      - discord
    networks:
      - ps2gg_internal
    volumes:
      - ../../:/app

networks:
  - ps2gg_internal
