version: '3.4'
services:
  discord:
    secrets:
      - discord_token
    networks:
      - ps2gg_internal

networks:
  ps2gg_internal:
    external: true

secrets:
  discord_token:
    external: true
